### ISSUE TITLE
Internal Server Error when running npm run watch

### ISSUE THREAD

**Issue by neilkyoung** [RickWong/react-isomorphic-starterkit#127]
I get the following error message when trying to run npm run watch:

```
Error: non-error thrown: [object Object]
[0]       at Object.module.exports.onerror (/Users/substance/Sites/react-isomorphic-starterkit/node_modules/koa/lib/context.js:107:40)
[0]       at run (/Users/substance/Sites/react-isomorphic-starterkit/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
[0]       at /Users/substance/Sites/react-isomorphic-starterkit/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
[0]       at flush (/Users/substance/Sites/react-isomorphic-starterkit/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
[0]       at doNTCallback0 (node.js:407:9)
[0]       at process._tickCallback (node.js:336:13)
```

This then yields an Internal Server Error in the browser.

**Comment by neilkyoung** [comment]
Looks to have resolved. Had problems with the hot update functionality where I had to add to add .js to the routes call in the handler.

**Comment by neilkyoung** [comment]
Unfortunately this has error has appeared again.

**Comment by neilkyoung** [comment]
Ok now I am definitely closing. It is hitting the rate limit for the github url. Not sure why as I only made a couple of calls but can just switch this off. Sorry for the confusion.
