### ISSUE TITLE
Had to downgrade to Node v5 for `npm run watch` to work

### ISSUE THREAD

**Issue by dijs** [RickWong/react-isomorphic-starterkit#130]
Here was the error I was seeing when using Node v6:

```
[1] ERROR in ../src/server.js
[1] Module build failed: TypeError: Path must be a string. Received undefined
[1]     at assertPath (path.js:7:11)
[1]     at Object.dirname (path.js:1324:5)
[1]     at /node_modules/babel-core/lib/transformation/file/options/option-manager.js:353:36
[1]     at /node_modules/babel-core/lib/transformation/file/options/option-manager.js:375:22
[1]     at Array.map (native)
[1]     at OptionManager.resolvePresets (/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
[1]     at OptionManager.mergePresets (/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
[1]     at OptionManager.mergeOptions (/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
[1]     at /node_modules/babel-core/lib/transformation/file/options/option-manager.js:349:14
[1]     at /node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:24
[1]     at Array.map (native)
[1]     at OptionManager.resolvePresets (/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
[1]     at OptionManager.mergePresets (/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
[1]     at OptionManager.mergeOptions (/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
[1]     at OptionManager.init (/node_modules/babel-core/lib/transformation/file/options/option-manager.js:465:10)
[1]     at File.initOptions (/node_modules/babel-core/lib/transformation/file/index.js:194:75)
[1]     at new File (/node_modules/babel-core/lib/transformation/file/index.js:123:22)
[1]     at Pipeline.transform (/node_modules/babel-core/lib/transformation/pipeline.js:45:16)
[1]     at transpile (/node_modules/babel-loader/index.js:14:22)
[1]     at Object.module.exports (/node_modules/babel-loader/index.js:88:12)
[1]  @ multi main
[0] Timed out waiting for dist/*.js after 30 seconds.
```

**Comment by musdy** [comment]
downgraded but still no luck with this

**Comment by danfairs** [comment]
Yup, I'm seeing the same too. Here's the output from my system, with all the detail:

```
boatman:react-isomorphic-starterkit dan$ npm run watch

> react-isomorphic-starterkit@5.4.0 watch /Users/dan/tmp/react-isomorphic-starterkit
> concurrently --kill-others "npm run watch-server-start" "npm run watch-server" "npm run watch-client"

[0]
[0] > react-isomorphic-starterkit@5.4.0 watch-server-start /Users/dan/tmp/react-isomorphic-starterkit
[0] > node node_modules/just-wait --pattern "dist/*.js" && npm run start
[0]
[1]
[1] > react-isomorphic-starterkit@5.4.0 watch-server /Users/dan/tmp/react-isomorphic-starterkit
[1] > webpack --watch --verbose --colors --display-error-details --config configs/webpack.server-watch.js
[1]
[2]
[2] > react-isomorphic-starterkit@5.4.0 watch-client /Users/dan/tmp/react-isomorphic-starterkit
[2] > webpack-dev-server --config configs/webpack.client-watch.js
[2]
[0] Waiting for dist/*.js (max 30 seconds)
[2] http://localhost:8080/webpack-dev-server/
[2] webpack result is served from http://localhost:8080/dist
[2] content is served from /Users/dan/tmp/react-isomorphic-starterkit
[1] Hash: d5b5febe5ee8c7bb8fba
[1] Version: webpack 1.12.14
[1] Time: 847ms
[1]    [0] multi main 40 bytes {0} [built] [1 error]
[1]     + 3 hidden modules
[1]
[1] ERROR in ../src/server.js
[1] Module build failed: TypeError: Path must be a string. Received undefined
[1]     at assertPath (path.js:7:11)
[1]     at Object.dirname (path.js:1326:5)
[1]     at /Users/dan/tmp/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:353:36
[1]     at /Users/dan/tmp/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:375:22
[1]     at Array.map (native)
[1]     at OptionManager.resolvePresets (/Users/dan/tmp/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
[1]     at OptionManager.mergePresets (/Users/dan/tmp/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
[1]     at OptionManager.mergeOptions (/Users/dan/tmp/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
[1]     at /Users/dan/tmp/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:349:14
[1]     at /Users/dan/tmp/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:24
[1]     at Array.map (native)
[1]     at OptionManager.resolvePresets (/Users/dan/tmp/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
[1]     at OptionManager.mergePresets (/Users/dan/tmp/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
[1]     at OptionManager.mergeOptions (/Users/dan/tmp/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
[1]     at OptionManager.init (/Users/dan/tmp/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:465:10)
[1]     at File.initOptions (/Users/dan/tmp/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/file/index.js:194:75)
[1]     at new File (/Users/dan/tmp/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/file/index.js:123:22)
[1]     at Pipeline.transform (/Users/dan/tmp/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/pipeline.js:45:16)
[1]     at transpile (/Users/dan/tmp/react-isomorphic-starterkit/node_modules/babel-loader/index.js:14:22)
[1]     at Object.module.exports (/Users/dan/tmp/react-isomorphic-starterkit/node_modules/babel-loader/index.js:88:12)
[1]  @ multi main
[0] Timed out waiting for dist/*.js after 30 seconds.
[0]
[0] npm
[0]  ERR! Darwin 15.6.0
[0] npm ERR! argv "/usr/local/Cellar/node/6.6.0/bin/node" "/usr/local/bin/npm" "run" "watch-server-start"
[0] npm ERR! node v6.6.0
[0] npm ERR! npm  v3.10.7
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! react-isomorphic-starterkit@5.4.0 watch-server-start: `node node_modules/just-wait --pattern "dist/*.js" && npm run start`
[0] npm ERR! Exit status 1
[0] npm ERR!
[0] npm ERR! Failed at the react-isomorphic-starterkit@5.4.0 watch-server-start script 'node node_modules/just-wait --pattern "dist/*.js" && npm run start'.
[0] npm ERR!
[0]  Make sure you have the latest version of node.js and npm installed.
[0] npm ERR! If you do, this is most likely a problem with the react-isomorphic-starterkit package,
[0] npm ERR! not with npm itself.
[0] npm ERR! Tell the author that this fails on your system:
[0] npm ERR!     node node_modules/just-wait --pattern "dist/*.js" && npm run start
[0] npm ERR! You can get information on how to open an issue for this project with:
[0] npm ERR!     npm bugs react-isomorphic-starterkit
[0] npm ERR! Or if that isn't available, you can get their info via:
[0] npm ERR!     npm owner ls react-isomorphic-starterkit
[0] npm ERR! There is likely additional logging output above.
[0]
[0] npm ERR! Please include the following file with any support request:
[0] npm ERR!     /Users/dan/tmp/react-isomorphic-starterkit/npm-debug.log
[0] npm run watch-server-start exited with code 1
--> Sending SIGTERM to other processes..
[1] npm run watch-server exited with code null
[2] npm run watch-client exited with code null

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.6.0/bin/node" "/usr/local/bin/npm" "run" "watch"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! react-isomorphic-starterkit@5.4.0 watch: `concurrently --kill-others "npm run watch-server-start" "npm run watch-server" "npm run watch-client"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-isomorphic-starterkit@5.4.0 watch script 'concurrently --kill-others "npm run watch-server-start" "npm run watch-server" "npm run watch-client"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-isomorphic-starterkit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently --kill-others "npm run watch-server-start" "npm run watch-server" "npm run watch-client"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-isomorphic-starterkit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-isomorphic-starterkit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dan/tmp/react-isomorphic-starterkit/npm-debug.log
```

Here's the content of the log file it mentioned:

```
boatman:react-isomorphic-starterkit dan$ cat /Users/dan/tmp/react-isomorphic-starterkit/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.6.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'watch' ]
2 info using npm@3.10.7
3 info using node@v6.6.0
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle react-isomorphic-starterkit@5.4.0~prewatch: react-isomorphic-starterkit@5.4.0
6 silly lifecycle react-isomorphic-starterkit@5.4.0~prewatch: no script for prewatch, continuing
7 info lifecycle react-isomorphic-starterkit@5.4.0~watch: react-isomorphic-starterkit@5.4.0
8 verbose lifecycle react-isomorphic-starterkit@5.4.0~watch: unsafe-perm in lifecycle true
9 verbose lifecycle react-isomorphic-starterkit@5.4.0~watch: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/dan/tmp/react-isomorphic-starterkit/node_modules/.bin:/usr/local/Cellar/node/6.6.0/bin:/Users/dan/google-cloud-sdk/bin:/usr/local/heroku/bin:/usr/local/share/python:/usr/local/bin:/usr/local/mysql/bin:/Users/dan/opt/bin:/Users/dan/opt/activator:/Users/dan/Unrest/golang/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
10 verbose lifecycle react-isomorphic-starterkit@5.4.0~watch: CWD: /Users/dan/tmp/react-isomorphic-starterkit
11 silly lifecycle react-isomorphic-starterkit@5.4.0~watch: Args: [ '-c',
11 silly lifecycle   'concurrently --kill-others "npm run watch-server-start" "npm run watch-server" "npm run watch-client"' ]
12 silly lifecycle react-isomorphic-starterkit@5.4.0~watch: Returned: code: 1  signal: null
13 info lifecycle react-isomorphic-starterkit@5.4.0~watch: Failed to exec watch script
14 verbose stack Error: react-isomorphic-starterkit@5.4.0 watch: `concurrently --kill-others "npm run watch-server-start" "npm run watch-server" "npm run watch-client"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-isomorphic-starterkit@5.4.0
16 verbose cwd /Users/dan/tmp/react-isomorphic-starterkit
17 error Darwin 15.6.0
18 error argv "/usr/local/Cellar/node/6.6.0/bin/node" "/usr/local/bin/npm" "run" "watch"
19 error node v6.6.0
20 error npm  v3.10.7
21 error code ELIFECYCLE
22 error react-isomorphic-starterkit@5.4.0 watch: `concurrently --kill-others "npm run watch-server-start" "npm run watch-server" "npm run watch-client"`
22 error Exit status 1
23 error Failed at the react-isomorphic-starterkit@5.4.0 watch script 'concurrently --kill-others "npm run watch-server-start" "npm run watch-server" "npm run watch-client"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-isomorphic-starterkit package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     concurrently --kill-others "npm run watch-server-start" "npm run watch-server" "npm run watch-client"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-isomorphic-starterkit
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-isomorphic-starterkit
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by hpgmiskin** [comment]
Upgrade to `babel-core@6.10.4` using `npm install babel-core@6.10.4 --save` as suggested in [this issue](https://github.com/webpack/webpack/issues/2463)

**Comment by snobojohan** [comment]
After babel upgrade I had to run `npm rebuild node-sass` and then it worked like a charm
