### ISSUE TITLE
(Linux / piping) App won't start

### ISSUE THREAD

**Issue by jmfurlott** [RickWong/react-isomorphic-starterkit#23]
Just pulled in a fresh clone and cannot get `npm run watch` to run correctly.  I have attached `npm start` which is the command that appears to be failing "within" `npm run watch`.

```
npm start

> react-isomorphic-starterkit@2.2.1 start /home/jmfurlott/work/react-isomorphic-starterkit-master
> NODE_PATH="./src" node ./babel.server

[piping] File ..gitignore.un has changed, reloading.
[piping] File .License.un has changed, reloading.
[piping] File .README.md.un has changed, reloading.
[piping] File .index.js.un has changed, reloading.
[piping] File .package.json.un has changed, reloading.
[piping] File .StreamCache.js.un has changed, reloading.
[piping] File .test-StreamCache.js.un has changed, reloading.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: IPC channel is already disconnected
    at process.target.disconnect (child_process.js:510:26)
    at Worker.disconnect (cluster.js:650:13)
    at Worker.onmessage (cluster.js:541:16)
    at process.<anonymous> (cluster.js:692:8)
    at process.emit (events.js:129:20)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)
[piping] File .History.md.un has changed, reloading.
[piping] File .Readme.md.un has changed, reloading.
[piping] File .package.json.un has changed, reloading.
[piping] File bogus.js has changed, reloading.
[piping] File .index.js.un has changed, reloading.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: watch ENOSPC
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at createFsWatchInstance (/home/jmfurlott/work/react-isomorphic-starterkit-master/node_modules/piping/node_modules/chokidar/lib/nodefs-handler.js:24:15)
    at setFsWatchListener (/home/jmfurlott/work/react-isomorphic-starterkit-master/node_modules/piping/node_modules/chokidar/lib/nodefs-handler.js:47:19)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/home/jmfurlott/work/react-isomorphic-starterkit-master/node_modules/piping/node_modules/chokidar/lib/nodefs-handler.js:177:15)
    at EventEmitter.NodeFsHandler._handleFile (/home/jmfurlott/work/react-isomorphic-starterkit-master/node_modules/piping/node_modules/chokidar/lib/nodefs-handler.js:201:8)
    at EventEmitter.<anonymous> (/home/jmfurlott/work/react-isomorphic-starterkit-master/node_modules/piping/node_modules/chokidar/lib/nodefs-handler.js:353:12)
    at FSReqWrap.oncomplete (fs.js:95:15)

npm ERR! Linux 3.19.0-13-generic
npm ERR! argv "/home/jmfurlott/.nvm/versions/node/v0.12.2/bin/node" "/home/jmfurlott/.nvm/versions/node/v0.12.2/bin/npm" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! react-isomorphic-starterkit@2.2.1 start: `NODE_PATH="./src" node ./babel.server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-isomorphic-starterkit@2.2.1 start script 'NODE_PATH="./src" node ./babel.server'.
npm ERR! This is most likely a problem with the react-isomorphic-starterkit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_PATH="./src" node ./babel.server
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-isomorphic-starterkit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jmfurlott/work/react-isomorphic-starterkit-master/npm-debug.log
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: IPC channel is already disconnected
    at process.target.disconnect (child_process.js:510:26)
    at Worker.disconnect (cluster.js:650:13)
    at Worker.onmessage (cluster.js:541:16)
    at process.<anonymous> (cluster.js:692:8)
    at process.emit (events.js:129:20)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)

```

**Comment by RickWong** [comment]
Just did a fresh install as well but I don't get this error. Can you do `npm uninstall piping; npm cache clean; npm install piping` and try again? If that doesn't work maybe `piping` isn't supported by your system? Definitely strange though.

**Comment by RickWong** [comment]
Also can you try this in `babel.server.js`:

``` js
if (!require("piping")({main: "./src/server.js", hook:true})) {
  ...
```

**Comment by Azaeres** [comment]
It looks like we're running into the system's watch limit here.  See http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc for more info.

**Comment by jmfurlott** [comment]
The first solution didn't help @RickWong, however, the second solution returned me the following: 

```
➜  react-isomorphic-starterkit git:(master) ✗ npm run watch

> react-isomorphic-starterkit@2.3.0 watch /home/jmfurlott/work/react-isomorphic-starterkit
> concurrent --kill-others 'npm run watch-client' 'npm run browser'

[0] 
[0] > react-isomorphic-starterkit@2.3.0 watch-client /home/jmfurlott/work/react-isomorphic-starterkit
[0] > webpack --verbose --colors --display-error-details --config webpack.client-watch.js && webpack-dev-server --config webpack.client-watch.js
[0] 
[0] 
[1] 
[1] > react-isomorphic-starterkit@2.3.0 browser /home/jmfurlott/work/react-isomorphic-starterkit
[1] > sleep 2; concurrent 'npm run start' 'npm run localhost'
[1] 
[1] 
[0] Hash: 67893fb848e71bde10d4
[0] Version: webpack 1.8.4
[0] Time: 1914ms
[0]     Asset     Size  Chunks             Chunk Names
[0] client.js  1.05 MB       0  [emitted]  main
[0]    [0] multi main 52 bytes {0} [built]
[0]     + 282 hidden modules
[0] 
[1] [1] 
[1] [1] > react-isomorphic-starterkit@2.3.0 localhost /home/jmfurlott/work/react-isomorphic-starterkit
[1] [1] > sleep 1; which open && open http://localhost:8000
[1] [1] 
[1] [1] 
[1] 
[1] [0] 
[1] [0] > react-isomorphic-starterkit@2.3.0 start /home/jmfurlott/work/react-isomorphic-starterkit
[1] [0] > NODE_PATH="./src" node ./babel.server
[1] [0] 
[1] [0] 
[1] 
[0] http://localhost:8080/webpack-dev-server/
[0] 
[0] webpack result is served from http://localhost:8080/dist/
[0] 
[0] content is served from ./static
[0] 
[1] [0] [piping] can't execute file: ./src/server.js
[1] [0] 
[1] 
[1] [0] [piping] error given was: /home/jmfurlott/work/react-isomorphic-starterkit/src/server.js:1
[1] [0] (function (exports, require, module, __filename, __dirname) { import {Server} 
[1] [0]                                                               ^^^^^^
[1] [0] SyntaxError: Unexpected reserved word
[1] [0]     at exports.runInThisContext (vm.js:73:16)
[1] [0]     at Module._compile (module.js:443:25)
[1] [0]     at Object.Module._extensions..js (module.js:478:10)
[1] [0]     at Module.load (module.js:355:32)
[1] [0]     at Module._load (module.js:310:12)
[1] [0]     at Function.module._load (/home/jmfurlott/work/react-isomorphic-starterkit/node_modules/piping/lib/launcher.js:32:16)
[1] [0]     at Module.require (module.js:365:17)
[1] [0]     at require (module.js:384:17)
[1] [0]     at Worker.<anonymous> (/home/jmfurlott/work/react-isomorphic-starterkit/node_modules/piping/lib/launcher.js:43:14)
[1] [0]     at Worker.emit (events.js:110:17)
[1] [0] 
[1] [0] [piping] further repeats of this error will be suppressed...
[1] [0] 
[1] 
[1] [1] /bin/open
[1] [1] 
[1] 
[1] [1] Couldn't get a file descriptor referring to the console
[1] [1] 
[1] 
[1] [1] 
[1] [1] 
[1] 
[1] [1] npm
[1] 
[1] [1]  
[1] 
[1] [1] ERR!
[1] 
[1] [1]  Linux 3.19.0-13-generic
[1] [1] 
[1] 
[1] [1] npm
[1] 
[1] [1]  
[1] 
[1] [1] ERR!
[1] 
[1] [1]  
[1] 
[1] [1] argv
[1] 
[1] [1]  "/home/jmfurlott/.nvm/versions/node/v0.12.2/bin/node" "/home/jmfurlott/.nvm/versions/node/v0.12.2/bin/npm" "run" "localhost"
[1] [1] 
[1] 
[1] [1] npm
[1] 
[1] [1]  
[1] 
[1] [1] ERR!
[1] 
[1] [1]  
[1] 
[1] [1] node
[1] 
[1] [1]  v0.12.2
[1] [1] 
[1] 
[1] [1] npm
[1] 
[1] [1]  
[1] 
[1] [1] ERR!
[1] 
[1] [1]  
[1] 
[1] [1] npm 
[1] 
[1] [1]  v2.7.4
[1] [1] 
[1] 
[1] [1] npm
[1] 
[1] [1]  
[1] 
[1] [1] ERR!
[1] 
[1] [1]  
[1] 
[1] [1] code
[1] 
[1] [1]  ELIFECYCLE
[1] [1] 
[1] 
[1] [1] npm
[1] 
[1] [1]  
[1] 
[1] [1] ERR!
[1] 
[1] [1]  react-isomorphic-starterkit@2.3.0 localhost: `sleep 1; which open && open http://localhost:8000`
[1] [1] 
[1] 
[1] [1] npm
[1] 
[1] [1]  
[1] 
[1] [1] ERR!
[1] 
[1] [1]  Exit status 1
[1] [1] 
[1] 
[1] [1] npm
[1] 
[1] [1]  
[1] 
[1] [1] ERR!
[1] 
[1] [1]  
[1] [1] 
[1] 
[1] [1] npm
[1] 
[1] [1]  
[1] 
[1] [1] ERR!
[1] 
[1] [1]  Failed at the react-isomorphic-starterkit@2.3.0 localhost script 'sleep 1; which open && open http://localhost:8000'.
[1] [1] 
[1] 
[1] [1] npm
[1] 
[1] [1]  
[1] 
[1] [1] ERR!
[1] 
[1] [1]  This is most likely a problem with the react-isomorphic-starterkit package,
[1] [1] 
[1] 
[1] [1] npm
[1] 
[1] [1]  
[1] 
[1] [1] ERR!
[1] 
[1] [1]  not with npm itself.
[1] [1] 
[1] 
[1] [1] npm
[1] 
[1] [1]  
[1] 
[1] [1] ERR!
[1] 
[1] [1]  Tell the author that this fails on your system:
[1] [1] 
[1] 
[1] [1] npm
[1] 
[1] [1]  
[1] 
[1] [1] ERR!
[1] 
[1] [1]      sleep 1; which open && open http://localhost:8000
[1] [1] 
[1] 
[1] [1] npm
[1] 
[1] [1]  
[1] 
[1] [1] ERR!
[1] 
[1] [1]  You can get their info via:
[1] [1] 
[1] 
[1] [1] npm
[1] 
[1] [1]  
[1] 
[1] [1] ERR!
[1] 
[1] [1]      npm owner ls react-isomorphic-starterkit
[1] [1] 
[1] 
[1] [1] npm
[1] 
[1] [1]  
[1] 
[1] [1] ERR!
[1] 
[1] [1]  There is likely additional logging output above.
[1] [1] 
[1] 
[1] [1] 
[1] [1] 
[1] 
[1] [1] npm
[1] 
[1] [1]  
[1] 
[1] [1] ERR!
[1] 
[1] [1]  Please include the following file with any support request:
[1] [1] 
[1] 
[1] [1] npm
[1] 
[1] [1]  
[1] 
[1] [1] ERR!
[1] 
[1] [1]      /home/jmfurlott/work/react-isomorphic-starterkit/npm-debug.log
[1] [1] 
[1] 
[1] [1] npm run localhost exited with code 1
[1] 
```

**Comment by jmfurlott** [comment]
I would find hard to believe my system doesn't support this `piping` package.  I am running Ubuntu.  The project  does, however, work on my OS X machine so it could most definitely be an issue with my machine

**Comment by Azaeres** [comment]
I ran into this running on Linux inside a Docker container, and didn't find a workaround.  `piping` depends on [`chokidar`](https://github.com/paulmillr/chokidar), which claims Linux support.  My guess is that `piping` is using `chokidar` in such a way that breaks support for Linux.  I unfortunately don't have much time to test.

**Comment by sergio-toro** [comment]
Same issue on Elementary OS (Ubuntu 14.04)

**Comment by lgt** [comment]
I face the same on my OSX is there any working workaround?

**Comment by DrMabuse23** [comment]
Hi i get an error after install and trying to run npm run watch 

```
npm run watch

> react-isomorphic-starterkit@2.5.3 watch /Users/drmabuse/htdocs/stammbaum
> node ./node_modules/concurrently/src/main.js --kill-others "npm run watch-client" "npm run start"

[0] 
[0] > react-isomorphic-starterkit@2.5.3 watch-client /Users/drmabuse/htdocs/stammbaum
[0] > node ./node_modules/webpack/bin/webpack.js --verbose --colors --display-error-details --config webpack.client-watch.js && node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --config webpack.client-watch.js
[0] 
[1] 
[1] > react-isomorphic-starterkit@2.5.3 start /Users/drmabuse/htdocs/stammbaum
[1] > NODE_PATH="./src" node ./babel.server
[1] 
[0] Hash: 48ddbb4b49e832176068
[0] Version: webpack 1.10.1
[0] Time: 2367ms
[0]    [0] multi main 52 bytes {0} [built] [1 error]
[0]     + 58 hidden modules
[0] 
[0] ERROR in ./src/client.js
[0] Module build failed: Error: /Users/drmabuse/htdocs/stammbaum/src/client.js: attachComments needs range information
[0]     at Object.attachComments (/Users/drmabuse/htdocs/stammbaum/node_modules/babel-core/node_modules/estraverse/estraverse.js:741:19)
[0]     at Object.exports.default (/Users/drmabuse/htdocs/stammbaum/node_modules/babel-core/lib/helpers/parse.js:80:27)
[0]     at File.parse (/Users/drmabuse/htdocs/stammbaum/node_modules/babel-core/lib/transformation/file/index.js:549:40)
[0]     at File.parseCode (/Users/drmabuse/htdocs/stammbaum/node_modules/babel-core/lib/transformation/file/index.js:658:20)
[0]     at /Users/drmabuse/htdocs/stammbaum/node_modules/babel-core/lib/transformation/pipeline.js:167:12
[0]     at File.wrap (/Users/drmabuse/htdocs/stammbaum/node_modules/babel-core/lib/transformation/file/index.js:614:16)
[0]     at Pipeline.transform (/Users/drmabuse/htdocs/stammbaum/node_modules/babel-core/lib/transformation/pipeline.js:165:17)
[0]     at transpile (/Users/drmabuse/htdocs/stammbaum/node_modules/babel-loader/index.js:12:22)
[0]     at Object.module.exports (/Users/drmabuse/htdocs/stammbaum/node_modules/babel-loader/index.js:69:12)
[0]  @ multi main
[1] [piping] can't execute file: /Users/drmabuse/htdocs/stammbaum/babel.server.js
[1] [piping] error given was: Error: /Users/drmabuse/htdocs/stammbaum/src/server.js: attachComments needs range information
[1]     at Object.attachComments (/Users/drmabuse/htdocs/stammbaum/node_modules/babel-core/node_modules/estraverse/estraverse.js:741:19)
[1]     at Object.exports.default (/Users/drmabuse/htdocs/stammbaum/node_modules/babel-core/lib/helpers/parse.js:80:27)
[1]     at File.parse (/Users/drmabuse/htdocs/stammbaum/node_modules/babel-core/lib/transformation/file/index.js:549:40)
[1]     at File.parseCode (/Users/drmabuse/htdocs/stammbaum/node_modules/babel-core/lib/transformation/file/index.js:658:20)
[1]     at /Users/drmabuse/htdocs/stammbaum/node_modules/babel-core/lib/transformation/pipeline.js:167:12
[1]     at File.wrap (/Users/drmabuse/htdocs/stammbaum/node_modules/babel-core/lib/transformation/file/index.js:614:16)
[1]     at Pipeline.transform (/Users/drmabuse/htdocs/stammbaum/node_modules/babel-core/lib/transformation/pipeline.js:165:17)
[1]     at Object.transformFileSync (/Users/drmabuse/htdocs/stammbaum/node_modules/babel-core/lib/api/node.js:133:37)
[1]     at compile (/Users/drmabuse/htdocs/stammbaum/node_modules/babel-core/lib/api/register/node.js:132:20)
[1]     at normalLoader (/Users/drmabuse/htdocs/stammbaum/node_modules/babel-core/lib/api/register/node.js:199:14)
[1] [piping] further repeats of this error will be suppressed...
[0] http://0.0.0.0:8080/
[0] webpack result is served from http://localhost:8080/dist/
[0] content is served from ./static

```

**Comment by RickWong** [comment]
Piping will be removed soon.
