### ISSUE TITLE
node_path & windows

### ISSUE THREAD

**Issue by gilesbradshaw** [RickWong/react-isomorphic-starterkit#39]
running in windows npm run watch

I get ...

Error occured when executing command: start'
Error: spawn 'npm ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

I think it has something to do with how NODE_PATH is set in package.json

**Comment by gilesbradshaw** [comment]
sorry duplicate of #1
