### ISSUE TITLE
Module build failed: Error

### ISSUE THREAD

**Issue by tylermadison** [RickWong/react-isomorphic-starterkit#53]
OSX 10.10.3, Node v0.12.7 - Cloned the repo, ran npm install and npm run watch:

``` javascript
0] ERROR in ./src/client.js
[0] Module build failed: Error: /Users/UserName/Documents/Development/repos/react-isomorphic-starterkit/src/client.js: attachComments needs range information
[0]     at Object.attachComments (/Users/UserName/Documents/Development/repos/react-isomorphic-starterkit/node_modules/babel-core/node_modules/estraverse/estraverse.js:741:19)
[0]     at Object.exports.default (/Users/UserName/Documents/Development/repos/react-isomorphic-starterkit/node_modules/babel-core/lib/helpers/parse.js:80:27)
[0]     at File.parse (/Users/UserName/Documents/Development/repos/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/file/index.js:549:40)
[0]     at File.parseCode (/Users/UserName/Documents/Development/repos/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/file/index.js:658:20)
[0]     at /Users/UserName/Documents/Development/repos/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/pipeline.js:167:12
[0]     at File.wrap (/Users/UserName/Documents/Development/repos/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/file/index.js:614:16)
[0]     at Pipeline.transform (/Users/UserName/Documents/Development/repos/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/pipeline.js:165:17)
[0]     at transpile (/Users/UserName/Documents/Development/repos/react-isomorphic-starterkit/node_modules/babel-loader/index.js:12:22)
[0]     at Object.module.exports (/Users/UserName/Documents/Development/repos/react-isomorphic-starterkit/node_modules/babel-loader/index.js:69:12)
[0]  @ multi main
[1] [piping] can't execute file: /Users/UserName/Documents/Development/repos/react-isomorphic-starterkit/babel.server.js
[1] [piping] error given was: Error: /Users/UserName/Documents/Development/repos/react-isomorphic-starterkit/src/server.js: attachComments needs range information
[1]     at Object.attachComments (/Users/UserName/Documents/Development/repos/react-isomorphic-starterkit/node_modules/babel-core/node_modules/estraverse/estraverse.js:741:19)
[1]     at Object.exports.default (/Users/UserName/Documents/Development/repos/react-isomorphic-starterkit/node_modules/babel-core/lib/helpers/parse.js:80:27)
[1]     at File.parse (/Users/UserName/Documents/Development/repos/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/file/index.js:549:40)
[1]     at File.parseCode (/Users/UserName/Documents/Development/repos/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/file/index.js:658:20)
[1]     at /Users/UserName/Documents/Development/repos/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/pipeline.js:167:12
[1]     at File.wrap (/Users/UserName/Documents/Development/repos/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/file/index.js:614:16)
[1]     at Pipeline.transform (/Users/UserName/Documents/Development/repos/react-isomorphic-starterkit/node_modules/babel-core/lib/transformation/pipeline.js:165:17)
[1]     at Object.transformFileSync (/Users/UserName/Documents/Development/repos/react-isomorphic-starterkit/node_modules/babel-core/lib/api/node.js:133:37)
[1]     at compile (/Users/UserName/Documents/Development/repos/react-isomorphic-starterkit/node_modules/babel-core/lib/api/register/node.js:132:20)
[1]     at normalLoader (/Users/UserName/Documents/Development/repos/react-isomorphic-starterkit/node_modules/babel-core/lib/api/register/node.js:199:14)
[1] [piping] further repeats of this error will be suppressed...
```

**Comment by pieterbergwerff** [comment]
I have the same error on OSX Yosemite 10.10.4 & Node v.0.10.36.
Seems like this is the problem: [piping] can't execute file: /Development/react-isomorphic-starterkit/babel.server.js

Contents of npm-debug.log: http://pastebin.com/zEz6eB1D

**Comment by lc3t35** [comment]
+1 same for me : OSX 10.8.5, Node 0.10.33

**Comment by tylersmalley** [comment]
The most recent commit is the cause, checkout 2770ab096f37e8b8308dcb6f44fca0f0d7111f22

**Comment by mathiasbno** [comment]
Had the same problem, seams to be related to Babel. 

I updated the Babel core version to the latest and it fixed the error. Have not tested the app fully, but seams to work for my purposes at least. 

To fix it run:

```
npm install bable-core --save-dev
```

My Babel verion is now set to:

```
"babel": "^5.6.23",
"babel-core": "^5.8.19",
```

Hope it helps.

**Comment by lc3t35** [comment]
Yep ! 

```
npm install babel-core --save-dev
```

Fix it -> no more error, thank you.

**Comment by bendman** [comment]
For anyone else having the `attachComments needs range information` problem, babel-core 5.8.3 seems to be the minimum version required to fix the issue.
