### ISSUE TITLE
Starter kit is not starting

### ISSUE THREAD

**Issue by droganov** [RickWong/react-isomorphic-starterkit#55]
Node version: v0.12.4, MacOS 10.10.4
Git clone, npm install, npm run watch ->

```
> react-isomorphic-starterkit@2.5.3 watch /pathto/www/exlab/react-isomorphic
> node ./node_modules/concurrently/src/main.js --kill-others "npm run watch-client" "npm run start"

[0] 
[0] > react-isomorphic-starterkit@2.5.3 watch-client /pathto/www/exlab/react-isomorphic
[0] > node ./node_modules/webpack/bin/webpack.js --verbose --colors --display-error-details --config webpack.client-watch.js && node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --config webpack.client-watch.js
[0] 
[1] 
[1] > react-isomorphic-starterkit@2.5.3 start /pathto/www/exlab/react-isomorphic
[1] > NODE_PATH="./src" node ./babel.server
[1] 
[0] Hash: 49f3a29840af95b8608f
[0] Version: webpack 1.10.1
[0] Time: 803ms
[0]    [0] multi main 52 bytes {0} [built] [1 error]
[0]     + 58 hidden modules
[0] 
[0] ERROR in ./src/client.js
[0] Module build failed: Error: /pathto/www/exlab/react-isomorphic/src/client.js: attachComments needs range information
[0]     at Object.attachComments (/pathto/www/exlab/react-isomorphic/node_modules/babel-core/node_modules/estraverse/estraverse.js:741:19)
[0]     at Object.exports.default (/pathto/www/exlab/react-isomorphic/node_modules/babel-core/lib/helpers/parse.js:80:27)
[0]     at File.parse (/pathto/www/exlab/react-isomorphic/node_modules/babel-core/lib/transformation/file/index.js:549:40)
[0]     at File.parseCode (/pathto/www/exlab/react-isomorphic/node_modules/babel-core/lib/transformation/file/index.js:658:20)
[0]     at /pathto/www/exlab/react-isomorphic/node_modules/babel-core/lib/transformation/pipeline.js:167:12
[0]     at File.wrap (/pathto/www/exlab/react-isomorphic/node_modules/babel-core/lib/transformation/file/index.js:614:16)
[0]     at Pipeline.transform (/pathto/www/exlab/react-isomorphic/node_modules/babel-core/lib/transformation/pipeline.js:165:17)
[0]     at transpile (/pathto/www/exlab/react-isomorphic/node_modules/babel-loader/index.js:12:22)
[0]     at Object.module.exports (/pathto/www/exlab/react-isomorphic/node_modules/babel-loader/index.js:69:12)
[0]  @ multi main
[1] [piping] can't execute file: /pathto/www/exlab/react-isomorphic/babel.server.js
[1] [piping] error given was: Error: /pathto/www/exlab/react-isomorphic/src/server.js: attachComments needs range information
[1]     at Object.attachComments (/pathto/www/exlab/react-isomorphic/node_modules/babel-core/node_modules/estraverse/estraverse.js:741:19)
[1]     at Object.exports.default (/pathto/www/exlab/react-isomorphic/node_modules/babel-core/lib/helpers/parse.js:80:27)
[1]     at File.parse (/pathto/www/exlab/react-isomorphic/node_modules/babel-core/lib/transformation/file/index.js:549:40)
[1]     at File.parseCode (/pathto/www/exlab/react-isomorphic/node_modules/babel-core/lib/transformation/file/index.js:658:20)
[1]     at /pathto/www/exlab/react-isomorphic/node_modules/babel-core/lib/transformation/pipeline.js:167:12
[1]     at File.wrap (/pathto/www/exlab/react-isomorphic/node_modules/babel-core/lib/transformation/file/index.js:614:16)
[1]     at Pipeline.transform (/pathto/www/exlab/react-isomorphic/node_modules/babel-core/lib/transformation/pipeline.js:165:17)
[1]     at Object.transformFileSync (/pathto/www/exlab/react-isomorphic/node_modules/babel-core/lib/api/node.js:133:37)
[1]     at compile (/pathto/www/exlab/react-isomorphic/node_modules/babel-core/lib/api/register/node.js:132:20)
[1]     at normalLoader (/pathto/www/exlab/react-isomorphic/node_modules/babel-core/lib/api/register/node.js:199:14)
[1] [piping] further repeats of this error will be suppressed...
[0] http://0.0.0.0:8080/
[0] webpack result is served from http://localhost:8080/dist/
[0] content is served from ./static

```

**Comment by tylermadison** [comment]
@droganov try `npm install babel-core --save-dev`

**Comment by droganov** [comment]
@tylermadison thank you, it works now

**Comment by tylermadison** [comment]
Opened a PR for this as well: https://github.com/RickWong/react-isomorphic-starterkit/pull/57
