### ISSUE TITLE
Documentation need to make npm watch work with node version less than 4

### ISSUE THREAD

**Issue by frob** [RickWong/react-isomorphic-starterkit#80]
When I run `npm run watch` and visit localhost:8080 nothing happens. The console outputs this message.

I installed exactly as the directions indicate. 

``` bash
npm install
npm run watch
```

This happens on the latest master and the 4.0.0 tag.

``` bash
[1] 
[1] > react-isomorphic-starterkit@4.0.0 start /var/www/app/react-isomorphic-starterkit
[1] > NODE_PATH="./src" node ./babel.server
[1] 
[1] /var/www/app/react-isomorphic-starterkit/node_modules/koa/node_modules/composition/index.js:111
[1] function* promiseToGenerator(promise) {
[1]         ^
[1] SyntaxError: Unexpected token *
[1]     at exports.runInThisContext (vm.js:73:16)
[1]     at Module._compile (module.js:443:25)
[1]     at Module._extensions..js (module.js:478:10)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/var/www/app/react-isomorphic-starterkit/node_modules/babel-core/lib/api/register/node.js:144:7)
[1]     at Module.load (module.js:355:32)
[1]     at Module._load (module.js:310:12)
[1]     at Function.module._load (/var/www/app/react-isomorphic-starterkit/node_modules/piping/lib/launcher.js:32:16)
[1]     at Module.require (module.js:365:17)
[1]     at require (module.js:384:17)
[1]     at Object.<anonymous> (/var/www/app/react-isomorphic-starterkit/node_modules/koa/lib/application.js:10:19)
```

**Comment by realalexhomer** [comment]
@frob Are you using node 4 or greater? Koa requires es2015 support to run.

Your getting an error when Koa tries to use a generator, which is an es2015 feature.

**Comment by frob** [comment]
I thought that babel was supposed to take care of that? Is there something we can put into the package.json to make sure this isn't going to happen?

**Comment by frob** [comment]
node v0.12.7 I will test with the latest.

**Comment by frob** [comment]
Yeah, confirmed that I do not get those errors on v4+

**Comment by RickWong** [comment]
It works with the `--harmony` flag for node 0.11/0.12 like this:

`NODE_PATH="./src" node --harmony ./babel.server`

**Comment by frob** [comment]
So the issue is documentation then.

**Comment by RickWong** [comment]
Thanks @frob for reporting this issue.

**Comment by favio41** [comment]
Hi guys, I get exactly the same error. I look into package.json to find the node version required and then I saw this:
`"node": ">=0.10.32"`

it shouldn't be something like this?
`"node": ">=0.11.16"`

cheers
