### ISSUE TITLE
npm run watch fails

### ISSUE THREAD

**Issue by bellicose100xp** [RickWong/react-isomorphic-starterkit#85]
Here's the log,

[0] 
[0] > react-isomorphic-starterkit@4.0.2 watch-client C:\Users\admin\WebstormProjects\react-isomorphic-starterkit
[0] > node ./node_modules/webpack/bin/webpack.js --verbose --colors --display-error-details --config webpack.client-watch.js && node .
/node_modules/webpack-dev-server/bin/webpack-dev-server.js --config webpack.client-watch.js
[0] 
[1] 
[1] > react-isomorphic-starterkit@4.0.2 start C:\Users\admin\WebstormProjects\react-isomorphic-starterkit
[1] > NODE_PATH="./src" node --harmony ./babel.server
[1] 
[1] 'NODE_PATH' is not recognized as an internal or external command,
[1] operable program or batch file.
[1] 
[1] npm
[1]  ERR! Windows_NT 10.0.10586
[1] npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "start"
[1] npm ERR! node v4.2.1
[1] npm ERR! npm  v2.14.7
[1] npm ERR!
[1] code ELIFECYCLE
[1] npm ERR! react-isomorphic-starterkit@4.0.2 start: `NODE_PATH="./src" node --harmony ./babel.server`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the react-isomorphic-starterkit@4.0.2 start script 'NODE_PATH="./src" node --harmony ./babel.server'.
[1] npm ERR! This is most likely a problem with the react-isomorphic-starterkit package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     NODE_PATH="./src" node --harmony ./babel.server
[1] npm ERR! You can get their info via:
[1] npm ERR!     npm owner ls react-isomorphic-starterkit
[1] npm ERR! There is likely additional logging output above.
[1] 
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     C:\Users\admin\WebstormProjects\react-isomorphic-starterkit\npm-debug.log
[1] npm run start exited with code 1
--> Sending SIGTERM to other processes..
[0] Hash: 3c53b09c7fa9dd3ef909
[0] Version: webpack 1.12.4
[0] Time: 2790ms
[0]     Asset     Size  Chunks             Chunk Names
[0] client.js  2.99 MB       0  [emitted]  main
[0]    [0] multi main 52 bytes {0} [built]
[0]     + 308 hidden modules
[0] events.js:141
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0] 
[0] Error: listen EADDRINUSE 127.0.0.1:8080
[0]     at Object.exports._errnoException (util.js:874:11)
[0]     at exports._exceptionWithHostPort (util.js:897:20)
[0]     at Server._listen2 (net.js:1234:14)
[0]     at listen (net.js:1270:10)
[0]     at net.js:1379:9
[0]     at GetAddrInfoReqWrap.asyncCallback [as callback](dns.js:63:16)
[0]     at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:82:10)
[0] 
[0] npm
[0] 
[0] ERR! Windows_NT 10.0.10586
[0] npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "watch-c
lient"
[0] npm
[0] ERR! node v4.2.1
[0] npm ERR! npm
[0]  v2.14.7
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! react-isomorphic-starterkit@4.0.2 watch-client: `node ./node_modules/webpack/bin/webpack.js --verbose --colors --display-
error-details --config webpack.client-watch.js && node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --config webpack.cl
ient-watch.js`
[0] npm ERR! Exit status 1
[0] npm ERR!
[0] npm ERR! Failed at the react-isomorphic-starterkit@4.0.2 watch-client script 'node ./node_modules/webpack/bin/webpack.js --verbose
 --colors --display-error-details --config webpack.client-watch.js && node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js
 --config webpack.client-watch.js'.
[0] npm ERR! This is most likely a problem with the react-isomorphic-starterkit package,
[0] npm ERR! not with npm itself.
[0] npm ERR! Tell the author that this fails on your system:
[0] npm ERR!
[0]      node ./node_modules/webpack/bin/webpack.js --verbose --colors --display-error-details --config webpack.client-watch.js && nod
e ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --config webpack.client-watch.js
[0] npm ERR! You can get their info via:
[0] npm ERR!     npm owner ls react-isomorphic-starterkit
[0] npm ERR! There is likely additional logging output above.
[0] 
[0] npm ERR! Please include the following file with any support request:
[0] npm ERR!     C:\Users\admin\WebstormProjects\react-isomorphic-starterkit\npm-debug.log
[0] npm run watch-client exited with code null

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "watch"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! react-isomorphic-starterkit@4.0.2 watch: `node ./node_modules/concurrently/src/main.js --kill-others "npm run watch-client" "
npm run start"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-isomorphic-starterkit@4.0.2 watch script 'node ./node_modules/concurrently/src/main.js --kill-others "npm
 run watch-client" "npm run start"'.
npm ERR! This is most likely a problem with the react-isomorphic-starterkit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/concurrently/src/main.js --kill-others "npm run watch-client" "npm run start"
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-isomorphic-starterkit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\admin\WebstormProjects\react-isomorphic-starterkit\npm-debug.log

**Comment by EvHaus** [comment]
Same issue here when running this on a Windows box. This is because you can't set environment variables the same way on Windows.

```
 NODE_PATH="./src" node --harmony ./babel.server
```

Must be changed to this on Windows:

```
set NODE_PATH="./src" node --harmony ./babel.server
```

Unfortunately, even after doing that, the package still doesn't work on Windows. The webpack server runs, but the node server fails with:

```
[1] npm run start exited with code 0
--> Sending SIGTERM to other processes..
```

**Comment by BenWildeman** [comment]
on windows you will need to do `SET NODE_PATH="./src" && node --harmony ./babel.server`

**Comment by RickWong** [comment]
Solved in https://github.com/RickWong/react-isomorphic-starterkit/pull/89
